### ISSUE TITLE
Add an option to filter functional difference heatmaps based on functional scores

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#108]
Can we add an option to filter hetmaps that plot functional differences between conditions based on functional scores for each of those conditions? In flu case that would be SA23 and SA26 entry scores.

**Comment by jbloom** [comment]
@Bernadetadad, this was already possible with the current code by adjusting the configuration. I have added an example to the `func_effects_config.yml` in the test example. Specifically, see the text adding `220210 effect` to `addtl_slider_stats` and `addtl_slider_stats_hide_not_filter` below:

```
func_effect_diffs:
  220210_vs_220302_comparison:
    condition_1:
      name: 220210
      selections:
        - LibA-220210-293T_ACE2-1
        - LibA-220210-293T_ACE2-2
    condition_2:
      name: 220302
      selections:
        - LibA-220302-293T_ACE2-1
        - LibA-220302-293T_ACE2-2
    avg_method: median
    per_selection_tooltips: true
    plot_kwargs:
      addtl_slider_stats:
        times_seen: 3
        difference_std: 2  # standard deviation difference across pairwise comparisons for mutation
        fraction_pairs_w_mutation: 1  # fraction of all pairs between conditions w mutation
        best_effect: -2  # effect must be >= for at least one condition
        220210 effect: null  # slider on effect in this condition, but no initial value
        220302 effect: null  # slider on effect in this condition, but no initial value
      addtl_slider_stats_hide_not_filter: [best_effect, 220210 effect, 220302 effect]
      addtl_slider_stats_as_max: [difference_std]
      heatmap_max_at_least: 1
      heatmap_min_at_least: -1
      init_floor_at_zero: false
      init_site_statistic: mean_abs
      site_zoom_bar_color_col: region  # supplied in the `site_numbering_map`
      slider_binding_range_kwargs:
        times_seen:
          step: 1
          min: 1
          max: 25
```
