### ISSUE TITLE
Sample naming clarification

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#21]
I'm a little confused about 'correct' sample naming here, I'm getting this keyerror:

<img width="1335" alt="image" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/22810662/93bdb481-9a29-4fad-9a13-fc6456804d44">
 
```
  Lib1-230613-antibody_sera_1-05:
    neut_standard_name: neut_standard
    prob_escape_filters: *prob_escape_filters_default
    polyclonal_params: *polyclonal_params_default
    escape_plot_kwargs: *escape_plot_kwargs_default
    plot_hide_stats: *plot_hide_stats_default
    no_antibody_sample: Lib1-230613-no-antibody_control
    antibody_samples:
     Lib1-230613-antibody_sera_1-05_0.000445:
      concentration: 0.000445
      use_in_fit: true
     Lib1-230613-antibody_sera_1-05_0.00178:
      concentration: 0.00178
      use_in_fit: true
     Lib1-230613-antibody_sera_1-05_0.00712:
      concentration: 0.00712
      use_in_fit: true
```

@jbloom also the pipeline seems to interpret dashes and underscores differently, can you clarify when to use which?
